In [ ]:
import pandas as pd
import json
import ast
import time
import base64
import os
from google import genai
from google.genai import types

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# !pip install google-genai

In [ ]:
!pip install -U transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.11.12)

In [ ]:
pip install --upgrade transformers accelerate

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.3)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.9.0+cu126)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.5.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.11.12)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)

In [ ]:
# df=pd.read_csv("/content/relevant_context.csv")
df=pd.read_csv("/content/Default_output_14_weeks.csv")

In [ ]:
df.shape

(58, 6)

In [ ]:
df.head()

,Question,Gold Answer,query,context_json_data,sys_prompt,minirag
0,Did Li Hua send a message to Jennifer thanking...,Yes,Did Li Hua send a message to Jennifer thanking...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Based on the information provided in the messa...
1,Did Yuriko ask Li Hua for help with her studio...,Yes,Did Yuriko ask Li Hua for help with her studio...,"[{""id"":0,""content"":""Time: 20260309_10:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Yes, according to the conversation, Yuriko did..."
2,Did Li Hua send a message to Jennifer asking i...,Yes,Did Li Hua send a message to Jennifer asking i...,"[{""id"":0,""content"":""Time: 20260309_12:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Yes, Li Hua did request a change in his traini..."
3,"What time does Li Hua watch the movie ""Overwat...",20260122,"What time does Li Hua watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260121_13:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversation shared, WolfgangSchu..."
4,"Who does Li Hua go to watch the movie ""Overwat...",Wolfgang,"Who does Li Hua go to watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260121_13:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,Based on the information provided in the conve...

In [ ]:
df['context_json_data'][0]

'[{"id":0,"content":"Time: 20260119_14:30\\nJenniferMoore: Hey Li Hua! \\ud83c\\udf89 Happy Lunar New Year! May this year bring you lots of joy and success. Keep up the fantastic work with your fitness goals\\u2014you\'re doing great! Let\'s stay committed and crush those resolutions together! \\ud83d\\udcaa\\u2728\\nLiHua: Thanks, Jennifer! Happy Lunar New Year to you too! \\ud83d\\udc09 I\'m totally hooked on my fitness journey. Can\'t wait to share some progress with you! Let\\u2019s keep motivating each other! \\ud83d\\ude0a\\ud83d\\udd25\\nJenniferMoore: That\\u2019s awesome to hear! I love your enthusiasm! \\ud83d\\udcaa Remember, consistency is key. If you need help with anything specific or new workout ideas, just let me know. Let\\u2019s keep pushing towards those goals! \\ud83c\\udfaf\\u2728\\nLiHua: Appreciate it, Jennifer! I\\u2019ll definitely reach out if I need some new ideas. Just trying to stay active and enjoy the process. Let\'s both crush it this year! \\ud83d\\ude4c\\ud83d\\ude01\\nJenniferMoore: Absolutely! Enjoying the journey is so important! \\ud83d\\udc96 Keep challenging yourself, and don\'t hesitate to share any wins, big or small. Let\'s make this year our best one yet! You got this! \\ud83c\\udf1f\\ud83d\\udcaa\\nLiHua: For sure! I\\u2019ll keep you updated on my progress. Looking forward to an amazing year ahead for both of us! \\ud83c\\udf89"},{"id":1,"content":"Time: 20260309_12:00\\nLiHua: Hey Jennifer! Hope you\\u2019re doing well! Quick question, is it possible to switch my class from Thursday to Friday this week? Let me know! Thanks!\\nJenniferMoore: Hey! I\'m doing great, thanks! \\ud83d\\ude0a Yes, we can definitely switch your class to Friday this week. What time works best for you?\\nLiHua: Awesome! How about the same time, 10:00am? Looking forward to it!\\nJenniferMoore: Perfect! I\'ve got you down for Friday at 10:00am. Can\'t wait to see you then! \\ud83d\\udcaa\\ud83c\\udffc\\nLiHua: Thanks, Jennifer! See you on Friday!"},{"id":2,"content":"Time: 20260204_15:00\\nLiHua: Hey Jennifer! Thanks for understanding my situation. So do you think we can change a training plan? That would really help me balance work and fitness better. Let me know what you think!\\nJenniferMoore: Absolutely, I can adjust the schedule for you! How about training twice a week instead? We can focus on efficiency and intensity to make the most of our sessions. Let me know if that works for you!\\nLiHua: That sounds great! I\'m all in for twice a week. Just let me know what days work best for you, and I\\u2019ll lock it in my calendar. Thanks a lot for being flexible!\\nJenniferMoore: Perfect! How about we do Tuesdays and Thursdays? That way, you get a solid rhythm going without it interfering too much with your work. Let me know if that suits you!\\nLiHua: Tuesdays and Thursdays work perfectly for me! Looking forward to our sessions and making the most out of them. Thanks again for your help!\\nJenniferMoore: You got it! I\\u2019m excited too! Together, we\'ll crush those goals! If you have any questions or need anything, just give me a shout. \\ud83d\\udcaa\\ud83d\\ude0a"},{"id":3,"content":"Time: 20260204_16:00\\nLiHua: Thanks so much for the new training schedule! I\\u2019m really excited to start this routine. I feel like it\\u2019s going to be a great boost for my fitness journey! \\ud83d\\udcaa\\ud83c\\udffc\\nJenniferMoore: You\\u2019re welcome! I\\u2019m pumped to see you take on this new challenge! Remember, consistency is key, and I\\u2019m here to support you every step of the way. Let\\u2019s crush those goals together! \\ud83d\\ude03\\ud83c\\udf1f\\nLiHua: Absolutely! I\\u2019m ready to give it my all. Can\\u2019t wait to see the progress we make together! Let\\u2019s do this! \\ud83c\\udf89\\nJenniferMoore: That\'s the spirit! Remember to listen to your body and stay hydrated. If you have any questions or need adjustments along the way, just shoot me a message. You\'ve got this! \\ud83c\\udfcb\\ufe0f\\u200d\\u2640\\ufe0f\\u2728\\nLiHua: Thanks for the reminder! I\\u2019ll definitely keep that in mind. I\\u2019ll reach out if I have any questions. Looking forward to our next session! \\ud83d\\udca7\\ud83d\\ude0a\\nJenniferMoore: Can\\u2019t wait for our next session either! Keep up the great work, and let\\u2019s continue pushing those limits! You\\u2019re doing amazing! \\ud83d\\ude4c\\ud83c\\udffc\\ud83d\\udca5"},{"id":4,"content":"Time: 20260318_15:00\\nLiHua: Hey Hailey! Your bread and milk are seriously amazing! \\ud83d\\ude0b Do you think you could send me some bread twice a week, like Mondays at 8am and Fridays at 8am? That would be awesome!\\nHaileyJohnson: Thanks so much for the love! \\ud83d\\udc96 I\\u2019ll definitely set you up for Monday and Friday deliveries at 8am. Fresh bread and milk will be waiting for you! \\ud83e\\udd56\\ud83e\\udd5b Can\\u2019t wait!\\nLiHua: Awesome! Thanks, Hailey! Looking forward to it! \\ud83d\\ude04\\nHaileyJohnson: You\\u2019re welcome! If you ever want to try something special or have any requests, just let me know. Enjoy! \\ud83c\\udf5e\\u2728\\nLiHua: Will do! You\'re the best! Enjoy your day! \\ud83d\\ude0a\\nHaileyJohnson: Thanks! You too, Li Hua! \\ud83c\\udf89\\ud83d\\udc69\\u200d\\ud83c\\udf73"},{"id":5,"content":"Time: 20260112_15:00\\nJenniferMoore: Hey Li Hua! \\ud83d\\udc4b Just wanted to say hi and introduce myself as your personal trainer. I\'m excited to work with you! \\ud83d\\udcaa \\n\\nI\'d love to discuss your training goals and come up with a plan that fits your needs. When are you available for a quick chat or session? \\ud83c\\udfcb\\ufe0f\\u200d\\u2642\\ufe0f\\nLiHua: Hey! Nice to meet you! I\'m looking forward to our training sessions too! \\ud83e\\udd73 I\'m usually free in the afternoons. How about we chat tomorrow around the same time? Let me know what works for you!\\nJenniferMoore: Sounds great! Tomorrow at 3 PM works for me! We can go over your goals and set up a training plan that suits you best. \\ud83d\\udcaa\\ud83d\\ude0a  Looking forward to it!\\nLiHua: Perfect! See you tomorrow at 3 PM then! Can\'t wait to kickstart this journey! \\ud83d\\udca5\\u2728 \\nJenniferMoore: Awesome! It\'s going to be a great journey together! If you have any specific goals or preferences before our chat, feel free to share them. See you tomorrow! \\ud83d\\ude80\\ud83d\\udcaa\\nLiHua: For sure! I\'ll think about it and let you know tomorrow. Can\'t wait!"},{"id":6,"content":"Time: 20260318_14:27\\nLiHua: Hey! So, I recently made a new friend, Yuriko. She\'s really cool! \\ud83c\\udfb8 \\n\\nWhat do you think about asking her to join us for our Sunday jam session? I think she\'d fit right in! Let me know if you\'re on board!\\nWolfgangSchulz: Sounds awesome! The more, the merrier, right? \\ud83d\\ude04 Let\'s bring her in on Sunday! Can\'t wait to jam! \\ud83c\\udfb6\\nLiHua: Cool! I\'ll reach out to her and see if she\'s interested. This is gonna be fun! \\ud83c\\udf89 \\nWolfgangSchulz: Yeah, for sure! It\'ll be great to have a fresh vibe. Let me know what she says! \\ud83c\\udfb5"},{"id":7,"content":"Time: 20260128_19:00\\nLiHua: Hey Jennifer! Just wanted to share my progress this week. I\'ve been sticking to the plan and feeling great! Do you think it\'s time to amp up the intensity for my workouts? Would love your thoughts!\\nJenniferMoore: Hey Li Hua! That\'s awesome to hear! If you feel like you\'re ready and your form is solid, we can definitely increase the intensity. Just let me know how you\'re feeling, and we can adjust the plan together! Keep up the great work! \\ud83d\\udcaa\\u2728\\nLiHua: Awesome! Thanks for the encouragement! I\'ve been feeling stronger, so I\\u2019m all in for an intensity boost! What do you suggest we change up for next time?\\nJenniferMoore: Great to hear you\'re feeling stronger! We can add some heavier weights or incorporate some high-intensity intervals into your routine. It\'ll keep things challenging and fun! Let\\u2019s aim for a mix to really push those limits! Excited for our next session! \\ud83d\\udd25\\ud83c\\udfcb\\ufe0f\\u200d\\u2642\\ufe0f\\nLiHua: Sounds perfect! I\'m really looking forward to it! Can\'t wait to see how it goes. Thanks again for your guidance!\\nJenniferMoore: You got it! Just keep that positive energy going, and you\'ll see awesome results. Let\\u2019s crush it next time! \\ud83d\\ude4c\\ud83d\\udca5"},{"id":8,"content":"Time: 20260311_10:15\\nYurikoYamamoto: Hi Li Hua! Hope you\'re doing well. Can you help me test the new feature for automatically scheduling available time on the studio homepage? I\\u2019d love to get your feedback. Thanks a bunch! \\ud83d\\ude0a\\nLiHua: Sure! I\'d be happy to help you with that. Just let me know what you need me to do, and I\'ll get right on it! \\ud83d\\udcc5\\nYurikoYamamoto: Great! Just visit the homepage and try to schedule a mock appointment using the new feature. Let me know if everything works smoothly or if there are any hiccups. Your input would really mean a lot to me!\\nLiHua: Sounds good! I\'ll check it out and let you know how it goes. Can\'t wait to give you feedback! \\ud83d\\ude0a\\nYurikoYamamoto: Thanks, Li Hua! I appreciate your help. Looking forward to hearing what you think!\\nLiHua: No problem at all! I\'ll dive into it right away. Talk soon! \\ud83c\\udfb8"},{"id":9,"content":"Time: 20260325_19:00\\nJenniferMoore: Hey Li Hua! \\ud83d\\ude0a I just wanted to check in on how you\'ve been feeling about your progress this month. I\\u2019m really impressed with your commitment! \\n\\nFor next month, I think focusing on strengthening your lower limbs would be awesome. It\\u2019ll really help with overall stability and performance. What do you think? \\ud83d\\udcaa\\nLiHua: Thanks, Jennifer! I\'ve actually been feeling pretty good about my progress. Lower limb exercises sound great. I\\u2019m definitely up for that! Do you have specific workouts in mind?\\nJenniferMoore: Awesome to hear you\'re feeling good! \\ud83c\\udf1f We can incorporate some squats, lunges, and maybe some deadlifts into our sessions. I\\u2019ll also make sure to add some balance work to keep things fun! How does that sound? \\ud83c\\udfcb\\ufe0f\\u200d\\u2642\\ufe0f\\nLiHua: Sounds perfect! I like the idea of adding balance work too. It\\u2019ll keep things interesting. I\\u2019m looking forward to the next session! Do you think we should adjust the plan to include additional reps or sets?\\nJenniferMoore: Absolutely! We can gradually increase the reps and sets each week to ensure you\'re building strength. \\ud83d\\udcc8 Just remember to listen to your body and we can always adjust if needed. I\\u2019ll prepare a new plan for our sessions! Let\\u2019s crush it! \\ud83d\\udca5"},{"id":10,"content":"Time: 20260114_17:00\\nJenniferMoore: Hey Li Hua! Just a quick reminder about our training session tomorrow. Don\'t forget to bring your water bottle! Looking forward to it! \\ud83d\\ude0a\\ud83d\\udcaa\\nLiHua: Got it! Thanks for the reminder! Can\'t wait for the session. It\'s always a blast! \\ud83d\\ude80\\ud83d\\udca6 See you!\\nJenniferMoore: Awesome! Glad to hear that! Let\'s smash those goals together! See you tomorrow! \\ud83d\\udc4a\\u2728\\nLiHua: Absolutely! Ready to give it my all! \\ud83c\\udfcb\\ufe0f\\u200d\\u2642\\ufe0f\\ud83d\\udca5 See you bright and early!\\nJenniferMoore: That\'s the spirit! Early bird gets the gains! \\ud83d\\ude04\\ud83c\\udf05 Let\'s make it a great session!\\nLiHua: For sure! It\'s going to be fun! \\ud83c\\udf1f\\ud83d\\udcaa Catch you tomorrow, bright and early!\\nJenniferMoore: Looking forward to it! Have a great evening, and get some rest! \\ud83d\\udca4\\ud83d\\udc9a"},{"id":11,"content":"Time: 20260205_13:00\\nLiHua: Hey Jennifer! Just checking in to see if you have any extra exercises I can do at home to complement my training schedule. Would love to maximize my progress! Thanks! \\ud83d\\ude0a\\nJenniferMoore: Hey Li Hua! Absolutely! Here are a few exercises you can do at home: \\n\\n1. Bodyweight squats - great for leg strength.\\n2. Plank holds - excellent for core stability.\\n3. Push-ups - works your chest, arms, and core.\\n4. Lunges - awesome for balance and leg strength.\\n5. Glute bridges - fantastic for your glutes and lower back.\\n\\nTry to aim for 3 sets of 10-15 reps for each exercise. You got this! \\ud83d\\udcaa\\ud83d\\ude0a Let me know if you have any questions!\\nLiHua: Thanks for the tips! I\'ll definitely include those in my routine. Do you think I should do them on off days or mix them in with my training?\\nJenniferMoore: It\'s great you\'re enthusiastic about adding them in! You can mix them into your training days for a boost or do them on your off days for active recovery. Just listen to your body! If you feel fatigued, stick to lighter sets or just focus on stretching and mobility work. Balance is key! \\ud83d\\ude0a\\ud83d\\udcaa  Let me know how it goes!\\nLiHua: Got it! I\\u2019ll find a good balance. Thanks again for your help! Looking forward to our next session! \\nJenniferMoore: You\\u2019re welcome! Can\\u2019t wait to see your progress! Keep pushing yourself and stay motivated. \\ud83d\\ude4c See you soon!"},{"id":12,"content":"Time: 20260323_08:00\\nHaileyJohnson: Good morning, Li Hua! \\ud83d\\ude0a Just a quick reminder that your fresh bread will be delivered today at 8am. Hope you enjoy it! \\ud83c\\udf5e\\u2728\\nLiHua: Thanks for the reminder! Can\\u2019t wait to dig into that bread. You always make the best stuff! \\ud83c\\udf5e\\ud83d\\ude04\\nHaileyJohnson: So happy to hear that! Your support means a lot. Let me know how you like it later! \\ud83e\\udd70\\ud83c\\udf5e\\nLiHua: Will do! Looking forward to it. Have a great day! \\ud83d\\ude04\\u2728\\nHaileyJohnson: Thanks, you too! Enjoy the bread! \\ud83c\\udf1f\\ud83e\\udd56"},{"id":13,"content":"Time: 20260105_11:00\\nLiHua: Hey! Just wanted to let you know that I\\u2019ve arrived in the city! \\ud83c\\udf89 How about we grab lunch together on the day after tomorrow, the 8th? Let me know what works for you! \\ud83d\\ude0a\\nWolfgangSchulz: Awesome! Can\'t wait to catch up. I\'ll look for a nice spot for us to hang out. See you on the 8th! \\ud83c\\udfb6\\u2728\\nLiHua: Perfect! I\'m looking forward to it! Let\\u2019s make it a fun day! \\ud83d\\ude04\\nWolfgangSchulz: Definitely! It\'s been too long. We\'re going to have such a great time! \\ud83c\\udf89"},{"id":14,"content":"Time: 20260403_15:00\\nJenniferMoore: Hey Li Hua! \\ud83c\\udf89 Just wanted to say how proud I am of your progress! You\'ve really put in the effort and it\'s showing. \\ud83d\\udcaa Can I share your amazing success story with the other clients? I think it would inspire them!\\nLiHua: Thanks, Jennifer! I really appreciate your support. \\ud83d\\ude0a Feel free to share my story with the others! I hope it can motivate them too.\\nJenniferMoore: Awesome! It really will! \\ud83d\\ude4c  Can\'t wait to celebrate more milestones together. You\\u2019re truly inspiring! \\nLiHua: Thanks a lot, Jennifer! Let\\u2019s keep pushing for more progress together! \\ud83d\\ude04\\nJenniferMoore: Absolutely! Let\'s crush those goals! \\ud83d\\udca5  Looking forward to our next session!"},{"id":15,"content":"Time: 20260112_10:00\\nLiHua: Hey! Wanna hit the gym together at 2pm today? I\'m thinking of signing up for a membership. Let me know!\\nWolfgangSchulz: Sounds like a plan! Let\\u2019s do it. It\\u2019ll be great to have a workout buddy. I\\u2019ll see you there!\\nLiHua: Awesome! Looking forward to it! \\ud83d\\udcaa Any specific workout you have in mind?\\nWolfgangSchulz: I was thinking we could start with some cardio, maybe hit the treadmill or bike for a bit. Then we can do some strength training. What do you think?\\nLiHua: That sounds perfect! Cardio to warm up, then some strength training. I\'m excited! See you at 2! \\ud83d\\ude04\\nWolfgangSchulz: Can\\u2019t wait! It\\u2019ll be fun to get back into it together. See you soon!"},{"id":16,"content":"Time: 20260330_18:00\\nAdamSmith: Hey Li Hua, just a quick reminder that rent is due soon. Let me know if you need any details!\\nLiHua: Thanks for the reminder, Adam! I\'ll get it sorted out soon. Hope you\'re having a great day!\\nAdamSmith: No problem! If you need anything or have questions, just reach out. Have a good one!\\nLiHua: Will do, Adam! Appreciate it. Catch you later!"},{"id":17,"content":"Time: 20260114_12:00\\nJenniferMoore: Hey Li Hua! \\ud83d\\ude0a How are you feeling about the exercises I sent? Let me know if you have any questions or if you need modifications for anything! \\ud83c\\udfcb\\ufe0f\\u200d\\u2640\\ufe0f\\nLiHua: Hey! I\'m feeling good about it! Thanks for the recommendations. I\\u2019ll definitely try to stick to them. Looking forward to our training session! \\ud83d\\udcaa\\ud83d\\ude0a\\nJenniferMoore: Awesome to hear, Li Hua! \\ud83d\\ude4c Keep me posted on how the exercises go. Remember, consistency is key! Can\'t wait to see your progress during our session! \\ud83d\\udca5\\nLiHua: Will do! I\\u2019ll keep practicing and I\\u2019m excited to show you what I can do. See you soon! \\ud83c\\udf1f\\nJenniferMoore: Great! I\\u2019m excited too! Let\\u2019s crush it together! If you need anything before our session, just shoot me a message! \\ud83d\\udcaa\\ud83d\\udd25"},{"id":18,"content":"Time: 20260122_16:00\\nJenniferMoore: Hey Li Hua! \\ud83d\\udcaa Here\\u2019s a list of lean meats you can incorporate into your meals:\\n\\n- Chicken breast \\ud83d\\udc14\\n- Turkey breast \\ud83e\\udd83\\n- Lean cuts of beef (like sirloin) \\ud83e\\udd69\\n- Fish (like salmon and tilapia) \\ud83c\\udfa3\\n- Tofu or tempeh for a plant-based option \\ud83c\\udf31\\n\\nFor snacks, how about:\\n\\n- Greek yogurt with honey and berries \\ud83c\\udf53\\n- Mixed nuts (almonds, walnuts, cashews) \\ud83e\\udd5c\\n- Cottage cheese with pineapple \\ud83c\\udf4d\\n- Hummus with carrot and cucumber sticks \\ud83e\\udd55\\ud83e\\udd52\\n\\nQuick Greek yogurt recipe: Just mix Greek yogurt with some honey, add your favorite fruits, and you\\u2019re good to go! Super tasty and packed with protein! \\n\\nLet me know if you want more ideas! \\ud83d\\ude0a\\nLiHua: Thanks, Jennifer! Those ideas sound great! I\\u2019ll definitely try the Greek yogurt with honey. Got any favorite fruit pairings? \\ud83c\\udf53\\ud83c\\udf4c\\nJenniferMoore: Absolutely! Some of my fave fruit pairings for Greek yogurt are:\\n\\n- Strawberries and blueberries for a berry blast! \\ud83c\\udf53\\ud83e\\uded0\\n- Sliced bananas with a sprinkle of cinnamon for sweetness! \\ud83c\\udf4c\\u2728\\n- Mixed berries with a drizzle of maple syrup for an extra treat! \\ud83c\\udf6f\\n- Chopped apples and a bit of peanut butter for a crunchy twist! \\ud83c\\udf4f\\ud83e\\udd5c\\n\\nFeel free to mix and match! They all taste awesome. Let me know what you think. \\ud83d\\ude0a\\nLiHua: Those combinations sound delicious! I think I\'ll go for the banana and cinnamon combo first. Thanks for the tips! Looking forward to adding these to my meals. By the way, how\'s everything going with your training sessions? Any new fitness goals? \\ud83c\\udfcb\\ufe0f\\u200d\\u2642\\ufe0f\\nJenniferMoore: Glad you\'re excited! The banana and cinnamon combo is a winner! As for my training sessions, I\'m currently focusing on building my endurance for an upcoming marathon. \\ud83c\\udfc3\\u200d\\u2640\\ufe0f I\\u2019m also trying some new strength routines to keep things fresh. What about you? Any goals you\\u2019re working on? \\ud83d\\udcaa\\nLiHua: I\'ve been really focused on building strength and stamina in my workouts! I\\u2019m aiming to crank up my weights and really push my limits. Also trying to improve my cardio for better overall fitness. I love how every session feels like a small victory! \\ud83c\\udfcb\\ufe0f\\u200d\\u2642\\ufe0f\\ud83c\\udf1f\\nJenniferMoore: That\\u2019s awesome to hear! Your dedication is inspiring! \\ud83d

In [ ]:
# from transformers import pipeline

# pipe = pipeline("text-generation", model="Qwen/Qwen2.5-3B-Instruct")
# messages = [
#     {"role": "user", "content": "Who are you?"},
# ]
# pipe(messages)

In [ ]:
# # Use a pipeline as a high-level helper
# from transformers import pipeline

# pipe = pipeline("text-generation", model="microsoft/Phi-3.5-mini-instruct")
# messages = [
#     {"role": "user", "content": "Who are you?"},
# ]
# pipe(messages)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

[{'generated_text': [{'role': 'user', 'content': 'Who are you?'},
   {'role': 'assistant',
    'content': " I am Phi, created by Microsoft. I'm an AI digital assistant designed to help answer questions and provide information based on your queries. How can I assist you today?"}]}]

In [ ]:
import os
from transformers import pipeline

# Read token from environment variable (recommended)
hf_token = ""

# Create pipeline with authentication
pipe = pipeline(
    "text-generation",
    model="meta-llama/Llama-3.2-3B-Instruct",
    token=hf_token,
)

messages = [
    {"role": "user", "content": "Who are you?"},
]

response = pipe(messages)
print(response)

config.json:   0%|          | 0.00/878 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/20.9k [00:00<?, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/1.46G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/54.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

Device set to use cuda:0
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

[{'generated_text': [{'role': 'user', 'content': 'Who are you?'}, {'role': 'assistant', 'content': 'I\'m an artificial intelligence model known as Llama. Llama stands for "Large Language Model Meta AI."'}]}]

In [ ]:
# import os
# from openai import OpenAI

# client = OpenAI(
#     base_url="https://router.huggingface.co/v1",
#     api_key='',
# )

# completion = client.chat.completions.create(
#     model="meta-llama/Llama-3.2-3B-Instruct:novita",
#     messages=[
#         {
#             "role": "user",
#             "content": "What is the capital of France?"
#         }
#     ],
# )

# print(completion.choices[0].message)

In [ ]:
def summarize_all_chunks(question, context):
    messages = [
        {"role": "system", "content": (
            "You are a summarizer. "
            "You will receive a list of context chunks and a question. "
            "TASK: Combine and summarize ALL the information from the chunks into a clear and long multi-sentence summary."
            "Focus more towards the relevance for the question asked. But include all the context in the summary."
            "Do NOT list chunks."
            "Output only the final summary as plain text."
        )},
        {"role": "user", "content": f"""
Few-shot example:

Context list:
1. "Gradient descent is an optimization algorithm used to minimize a loss function."
2. "It updates parameters by moving in the direction of the negative gradient."
3. "Python is a programming language."

Output:
"Gradient descent is an optimization method that reduces a loss function by iteratively adjusting parameters in the direction of the negative gradient. It is widely used in machine learning and numerical optimization."

Now summarize the following:
Context list: {context}
Question: {question}
"""}
    ]

    a = pipe(messages)
    return a[0]['generated_text'][2]['content']

In [ ]:
# def summarize_all_chunks(question, context):
#     messages = [
#         {"role": "system", "content": (
#             "You are a summarizer. "
#             "You will receive a list of context chunks and a question. "
#             "TASK: Combine and summarize ALL the information from the chunks into a clear and long multi-sentence summary."
#             "Focus more towards the relevance for the question asked. But include all the context in the summary."
#             "Do NOT list chunks."
#             "Output only the final summary as plain text."
#         )},
#         {"role": "user", "content": f"""
# Few-shot example:

# Context list:
# 1. "Gradient descent is an optimization algorithm used to minimize a loss function."
# 2. "It updates parameters by moving in the direction of the negative gradient."
# 3. "Python is a programming language."

# Output:
# "Gradient descent is an optimization method that reduces a loss function by iteratively adjusting parameters in the direction of the negative gradient. It is widely used in machine learning and numerical optimization."

# Now summarize the following:
# Context list: {context}
# Question: {question}
# """}
#     ]

#     completion = client.chat.completions.create(
#     model="meta-llama/Llama-3.2-3B-Instruct:novita",
#     messages=messages,
# )

#     return completion.choices[0].message.content

In [ ]:
b=summarize_all_chunks(df['Question'][0], df['context_json_data'][0])

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

In [ ]:
df['Question'][0]

'Did Li Hua send a message to Jennifer thanking her for the new training schedule before he requested a change in his training schedule for Thursday?'

In [ ]:
print(b)

Li Hua had sent a message to Jennifer Moore thanking her for the new training schedule before he requested a change in his training schedule for Thursday. In a conversation on February 4th, Li Hua expressed his gratitude for the new training plan that Jennifer had provided, stating that it was great and that he felt like it would really help with his fitness goals. This message was sent about a week before he asked Jennifer to change his class from Thursday to Friday, as mentioned in a conversation on February 9th.

In [ ]:
df['relevant_context']=df.apply(lambda x: summarize_all_chunks(x['Question'], x['context_json_data']), axis=1)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

In [ ]:
df

,Question,Gold Answer,query,context_json_data,sys_prompt,minirag,relevant_context
0,Did Li Hua send a message to Jennifer thanking...,Yes,Did Li Hua send a message to Jennifer thanking...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Based on the information provided in the messa...,Li Hua sent a message to Jennifer thanking her...
1,Did Yuriko ask Li Hua for help with her studio...,Yes,Did Yuriko ask Li Hua for help with her studio...,"[{""id"":0,""content"":""Time: 20260309_10:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Yes, according to the conversation, Yuriko did...",Yuriko did ask Li Hua for help with her studio...
2,Did Li Hua send a message to Jennifer asking i...,Yes,Did Li Hua send a message to Jennifer asking i...,"[{""id"":0,""content"":""Time: 20260309_12:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Yes, Li Hua did request a change in his traini...",Li Hua sent a message to Jennifer asking if he...
3,"What time does Li Hua watch the movie ""Overwat...",20260122,"What time does Li Hua watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260121_13:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversation shared, WolfgangSchu...","Li Hua plans to watch the movie ""Overwatch 3"" ..."
4,"Who does Li Hua go to watch the movie ""Overwat...",Wolfgang,"Who does Li Hua go to watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260121_13:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,Based on the information provided in the conve...,"Li Hua plans to watch the movie ""Overwatch 3"" ..."
5,Who wished Li Hua a happy Lunar New Year?,Adam Smith & Jennifer Moore & Wolfgang Schulz,Who wished Li Hua a happy Lunar New Year?,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,"In the conversation, Jennifer Moore wished Li ...",Li Hua received happy Lunar New Year wishes fr...
6,Who introduced the bread delivery service and ...,HaileyJohnson,NaN,NaN,NaN,CUDA out of memory. Tried to allocate 2.14 GiB...,I couldn't find any information in the provide...
7,What is the opportunity that makes Wolfgang an...,LiHua introduce them to each other by saying t...,NaN,NaN,NaN,CUDA out of memory. Tried to allocate 2.01 GiB...,I couldn't find any relevant information in th...
8,What was the content of the first-ever deliver...,a fresh sourdough loaf and a bottle of milk an...,What was the content of the first-ever deliver...,"[{""id"":0,""content"":""Time: 20260314_17:00\nHail...",---Role---\n\nYou are a helpful assistant resp...,The first-ever delivery from Hailey Johnson to...,Hailey initially offered LiHua a doorstep deli...
9,Did Li Hua send a message to Wolfgang Schulz s...,Yes,Did Li Hua send a message to Wolfgang Schulz s...,"[{""id"":0,""content"":""Time: 20260318_14:27\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"No, there is no mention in the provided data o...",Li Hua had previously sent a message to Wolfga...
10,Did Li Hua provide feedback to Jennifer Moore ...,No,Did Li Hua provide feedback to Jennifer Moore ...,"[{""id"":0,""content"":""Time: 20260115_16:45\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"In the conversation, Li Hua did not explicitly...",Li Hua provided feedback to Jennifer Moore on ...
11,Did Li Hua's complaint about the customer who ...,No,Did Li Hua's complaint about the customer who ...,"[{""id"":0,""content"":""Time: 20260330_08:00\nHail...",---Role---\n\nYou are a helpful assistant resp...,The complaint about the customer modifying the...,Li Hua's complaint about a client modifying th...
12,Did Yuriko tell Li Hua about booking a seat at...,Yes,Did Yuriko tell Li Hua about booking a seat at...,"[{""id"":0,""content"":""Time: 20260309_10:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Yes, according to the conversation, Yuriko inf...","Yuriko had previously booked a seat at ""Centra..."
13,What time does Li Hua check in with Adam about...,17:30,What time does Li Hua check in with Adam about...,"[{""id"":0,""content"":""Time: 20260105_14:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua checks in with Adam about the details f...,Li Hua checks in with Adam about moving in aro...
14,When was the first time Li Hua had dinner with...,20260108,When was the first time Li Hua had dinner with...,"[{""id"":0,""content"":""Time: 20260105_11:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,The first documented instance of Li Hua and Wo...,Li Hua and Wolfgang first had dinner together ...
15,Where was the first time Li Hua had dinner wit...,the cozy café downtown,Where was the first time Li Hua had dinner wit...,"[{""id"":0,""content"":""Time: 20260105_11:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,The first recorded instance of Li Hua having d...,Li Hua and Wolfgang had dinner at a cozy café ...
16,What time is Li Hua's lunch with Wolfgang Schu...,20260108,What time is Li Hua's lunch with Wolfgang Schu...,"[{""id"":0,""content"":""Time: 20260108_11:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversation, Li Hua and Wolf...",Li Hua's lunch with Wolfgang Schulz at the coz...
17,What is the Wi-Fi password at Li Hua's house?,Family123,What is the Wi-Fi password at Li Hua's house?,"[{""id"":0,""content"":""Time: 20260106_09:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the information provided, the Wi-Fi p...","Li Hua's house has a Wi-Fi password of ""Family..."
18,What does Adam say about having friends over?,having friends over occasionally is fine,What does Adam say about having friends over?,"[{""id"":0,""content"":""Time: 20260106_09:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"In the conversation, Adam provides detailed in...",AdamSmith mentioned that having friends over o...
19,What house rule does Adam mention?,keep noise to a minimum during late hours,What house rule does Adam mention?,"[{""id"":0,""content"":""Time: 20260109_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Adam mentions a couple of house rules in the c...,Adam mentions that Li Hua should keep noise to...
20,What does Li Hua report to Adam on January 6th?,the water tab in the apartment is broken,What does Li Hua report to Adam on January 6th?,"[{""id"":0,""content"":""Time: 20260330_18:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,"On January 6th, at 9:00 AM, Li Hua communicate...",Li Hua reports to Adam on January 6th that she...
21,When does Adam confirm the plumber will arrive?,tomorrow at 10 AM,When does Adam confirm the plumber will arrive?,"[{""id"":0,""content"":""Time: 20260106_15:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversation, Adam confirms t...",Adam confirms that the plumber will arrive tom...
22,What does Li Hua ask Adam about the door hinge?,a small repair,What does Li Hua ask Adam about the door hinge?,"[{""id"":0,""content"":""Time: 20260109_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua initially reached out to Adam Smith abo...,Li Hua asked Adam about the possibility of get...
23,What is the name of the gym that Wolfgang reco...,FitZone,What is the name of the gym that Wolfgang reco...,"[{""id"":0,""content"":""Time: 20260318_14:27\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Wolfgang recommended LiHua to go to a gym call...,Wolfgang recommended that LiHua check out FitZ...
24,When does Li Hua ask Jennifer Moore about adju...,20260122,When does Li Hua ask Jennifer Moore about adju...,"[{""id"":0,""content"":""Time: 20260115_16:45\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua reaches out to Jennifer Moore about adj...,Li Hua asks Jennifer Moore about adjusting the...
25,"What time does Li Hua watch the movie ""Overwat...",20260122,"What time does Li Hua watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260121_13:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,Based on the information provided in the conve...,Li Hua and Wolfgang Schulz plan to catch the 7...
26,"Who does Li Hua go to watch the movie ""Overwat...",Wolfgang,"Who does Li Hua go to watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260118_12:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversation provided, WolfgangSc...","Li Hua goes to watch the movie ""Overwatch 3"" w..."
27,When does Li Hua plan to celebrate Chinese Lun...,20260118,When does Li Hua plan to celebrate Chinese Lun...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua plans to celebrate Chinese Lunar New Ye...,Li Hua plans to celebrate Chinese Lunar New Ye...
28,What does Li Hua plan to celebrate Chinese Lun...,dumplings,What does Li Hua plan to celebrate Chinese Lun...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua plans to celebrate Chinese Lunar New Ye...,Li Hua plans to celebrate Chinese Lunar New Ye...
29,Who does Li Hua plan to celebrate Chinese Luna...,Wolfgang,Who does Li Hua plan to celebrate Chinese Luna...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua plans to celebrate Chinese Lunar New Ye...,Li Hua plans to celebrate Chinese Lunar New Ye...
30,Li Hua accidentally broke a light fixture once...,I'll arrange for a professional to take a look,Li Hua accidentally broke a light fixture once...,"[{""id"":0,""content"":""Time: 20260108_19:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"In a conversation dated 20260108_19:00, Li Hua...",Li Hua accidentally broke a light fixture in t...
31,Li Hua has a difficult client. When did he sol...,20260209,Li Hua has a difficult client. When did he sol...,"[{""id"":0,""content"":""Time: 20260210_21:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"According to the records, Li Hua solved the di...","Li Hua secured that difficult client, but the ..."
32,When did Li Hua express frustration about a cl...,20260131_14:00,When did Li Hua express frustration about a cl...,"[{""id"":0,""content"":""Time: 20260311_10:15\nYuri...",---Role---\n\nYou are a helpful assistant resp...,Li Hua expressed frustration about a client ch...,Li Hua expressed frustration about a client ch...
33,Who suggested Li Hua keep a clear log of all t...,Wolfgang Schulz,Who suggested Li Hua keep a clear log of all t...,"[{""id"":0,""content"":""Time: 20260123_17:30\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversation, Wolfgang Schulz...",Li Hua suggested keeping a clear log of all th...
34,What did Wolfgang Schulz suggest Li Hua to do ...,keep a clear log of all the changes requested ...,What did Wolfgang Schulz suggest Li Hua to do ...,"[{""id"":0,""content"":""Time: 20260105_11:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,When Li Hua faced a challenging client who kep...,Wolfgang Schulz suggested that Li Hua should k...
35,What does Li Hua plan to do to clear their head?,go for a walk and find a new café,What does Li Hua plan to do to clear their head?,"[{""id"":0,""content"":""Time: 20260311_10:15\nYuri...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversations recorded, Li Hua re...",Li Hua plans to go to a gym or fitness center ...
36,What is the name of the café Wolfgang Schulz r...,The Java Spot,What is the name of the café Wolfgang Schulz r...,"[{""id"":0,""content"":""Time: 20260108_11:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,According to the interactions detailed in the ...,"Wolfgang Schulz recommends a café called ""The ..."
37,Can Li Hua hang his artworks on the wall?,Yes,Can Li Hua hang his artworks on the wall?,"[{""id"":0,""content"":""Time: 20260201_20:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversation, Li Hua can indeed h...",Li Hua had inquired about hanging his artworks...
38,What does Adam Smith suggest Li Hua use to han...,use removable hooks,What does Adam Smith suggest Li Hua use to han...,"[{""id"":0,""content"":""Time: 20260201_20:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,According to the conversations between Li Hua ...,Adam Smith suggests that Li Hua use removable ...
39,How many times does Li Hua train per week now?,2,How many times does Li Hua train per week now?,"[{""id"":0,""content"":""Time: 20260204_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the interactions provided, there isn'...","Li Hua now trains twice a week, with sessions ..."
40,When did Li Hua change the training plan?,20260204,When did Li Hua change the training plan?,"[{""id"":0,""content"":""Time: 20260112_15:00\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua did not explicitly change the training ...,Li Hua changed the training plan to train twic...
41,What days does Li Hua takes for the training s...,Tuesdays and Thursdays,What days does Li Hua takes for the training s...,"[{""id"":0,""content"":""Time: 20260204_15:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversations provided, there are...","Li Hua takes training sessions twice a week, o..."
42,When did Li Hua ask Jennifer Moore for tips on...,20260206_16:00,When did Li Hua ask Jennifer Moore for tips on...,"[{""id"":0,""content"":""Time: 20260206_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua asked Jennifer Moore for tips on dealin...,Li Hua asked Jennifer Moore for tips on dealin...
43,What are some of Jennifer Moore's tips for dea...,hydration&active recovery&stretching&foam roll...,What are some of Jennifer Moore's tips for dea...,"[{""id"":0,""content"":""Time: 20260206_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Jennifer Moore provides several tips for deali...,Jennifer Moore suggests that dealing with musc...
44,Why did Li Hua ask for extra exercises to do a...,to complement his training schedule,Why did Li Hua ask for extra exercises to do a...,"[{""id"":0,""content"":""Time: 20260325_19:00\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua reached out to Jennifer Moore for extra...,Li Hua asked for extra exercises to do at home...
45,What exercises did Jennifer Moore suggest Li H...,bodyweight squats& plank holds&push-ups&lunges...,What exercises did Jennifer Moore suggest Li H...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Based on the conversations documented in the d...,Jennifer Moore suggested that Li Hua do the fo...
46,What is Adam Smith's condition for Li Hua to a...,must be reversible and not damage anything,What is Adam Smith's condition for Li Hua to a...,"[{""id"":0,""content"":""Time: 20260108_19:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversations, Adam Smith has...",Adam Smith has stated that as long as the deco...
47,When was the first time Wolfgang went to Li Hu...,20260221,When was the first time Wolfgang went to Li Hu...,"[{""id"":0,""content"":""Time: 20260301_13:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,The first mention of Wolfgang visiting Li Hua'...,"Based on the provided conversation history, th..."
48,What ideas did Wolfgang Schulz suggest for Li ...,good lighting&soundproofing&a comfy chair,What ideas did Wolfgang Schulz suggest for Li ...,"[{""id"":0,""content"":""Time: 20260105_11:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,In the conversations regarding Wolfgang Schulz...,Wolfgang Schulz suggested several ideas for Li...
49,Why did Adam remind Li Hua not to play guitar ...,a few neighbors have mentioned they're hearing...,Why did Adam remind Li Hua not to play guitar ...,"[{""id"":0,""content"":""Time: 20260218_18:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,Adam reminded Li Hua not to play guitar late a...,Adam reminded Li Hua not to play guitar late a...
50,What type of ambiance does YurikoYamamoto want...,more welcoming and engaging,NaN,NaN,NaN,CUDA out of memory. Tried to allocate 2.10 GiB...,"Unfortunately, there is no context provided, r..."
51,When did Li Hua invite Adam Smith to check the...,20260223_19:00,When did Li Hua invite Adam Smith to check the...,"[{""id"":0,""content"":""Time: 20260223_17:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua invited Adam Smith to check the progres...,Li Hua invited Adam Smith to check the basemen...
52,What is the name of the café where Li Hua and ...,Central Perk,What is the name of the café where Li Hua and ...,"[{""id"":0,""content"":""Time: 20260312_16:00\nYuri...",---Role---\n\nYou are a helpful assistant resp...,Li Hua and YurikoYamamoto first met at Central...,Li Hua and YurikoYamamoto first met to discuss...
53,What is the essence of YurikoYamamoto Li Hua i...,speech therapy,What is the essence of YurikoYamamoto Li Hua i...,"[{""id"":0,""content"":""Time: 20260311_14:30\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,YurikoYamamoto is seeking Li Hua's assistance ...,YurikoYamamoto is working on improving her spe...
54,What type of instrument does Li Hua play in th...,guitar,NaN,NaN,NaN,CUDA out of memory. Tried to allocate 2.07 GiB...,I couldn't find any information on Li Hua or t...
55,When did Adam Smith inform Li Hua about potent...,20260301_13:00,When did Adam Smith inform Li Hua about potent...,"[{""id"":0,""content"":""Time: 20260301_13:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversation, Adam Smith info...",Adam Smith informed Li Hua about potential iss...
56,When did Li Hua inform Adam Smith that the ren...,20260301_10:00,When did Li Hua inform Adam Smith that the ren...,"[{""id"":0,""content"":""Time: 20260331_17:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua informed Adam Smith about the transfer ...,Li Hua informed Adam Smith that the rent was t...
57,When is the music concert that Wolfgang invite...,20260307_18:00,NaN,NaN,NaN,CUDA out of memory. Tried to allocate 9.22 GiB...,"There is no context information provided, as t..."

In [ ]:
df.to_csv("relevant_context.csv", index=False)

In [ ]:
df

,Question,Gold Answer,query,context_json_data,sys_prompt,minirag,relevant_context
0,Did Li Hua send a message to Jennifer thanking...,Yes,Did Li Hua send a message to Jennifer thanking...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Based on the information provided in the messa...,Li Hua sent a message to Jennifer thanking her...
1,Did Yuriko ask Li Hua for help with her studio...,Yes,Did Yuriko ask Li Hua for help with her studio...,"[{""id"":0,""content"":""Time: 20260309_10:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Yes, according to the conversation, Yuriko did...",Yuriko did ask Li Hua for help with her studio...
2,Did Li Hua send a message to Jennifer asking i...,Yes,Did Li Hua send a message to Jennifer asking i...,"[{""id"":0,""content"":""Time: 20260309_12:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Yes, Li Hua did request a change in his traini...",Li Hua sent a message to Jennifer asking if he...
3,"What time does Li Hua watch the movie ""Overwat...",20260122,"What time does Li Hua watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260121_13:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversation shared, WolfgangSchu...","Li Hua plans to watch the movie ""Overwatch 3"" ..."
4,"Who does Li Hua go to watch the movie ""Overwat...",Wolfgang,"Who does Li Hua go to watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260121_13:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,Based on the information provided in the conve...,"Li Hua plans to watch the movie ""Overwatch 3"" ..."
5,Who wished Li Hua a happy Lunar New Year?,Adam Smith & Jennifer Moore & Wolfgang Schulz,Who wished Li Hua a happy Lunar New Year?,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,"In the conversation, Jennifer Moore wished Li ...",Li Hua received happy Lunar New Year wishes fr...
6,Who introduced the bread delivery service and ...,HaileyJohnson,NaN,NaN,NaN,CUDA out of memory. Tried to allocate 2.14 GiB...,I couldn't find any information in the provide...
7,What is the opportunity that makes Wolfgang an...,LiHua introduce them to each other by saying t...,NaN,NaN,NaN,CUDA out of memory. Tried to allocate 2.01 GiB...,I couldn't find any relevant information in th...
8,What was the content of the first-ever deliver...,a fresh sourdough loaf and a bottle of milk an...,What was the content of the first-ever deliver...,"[{""id"":0,""content"":""Time: 20260314_17:00\nHail...",---Role---\n\nYou are a helpful assistant resp...,The first-ever delivery from Hailey Johnson to...,Hailey initially offered LiHua a doorstep deli...
9,Did Li Hua send a message to Wolfgang Schulz s...,Yes,Did Li Hua send a message to Wolfgang Schulz s...,"[{""id"":0,""content"":""Time: 20260318_14:27\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"No, there is no mention in the provided data o...",Li Hua had previously sent a message to Wolfga...
10,Did Li Hua provide feedback to Jennifer Moore ...,No,Did Li Hua provide feedback to Jennifer Moore ...,"[{""id"":0,""content"":""Time: 20260115_16:45\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"In the conversation, Li Hua did not explicitly...",Li Hua provided feedback to Jennifer Moore on ...
11,Did Li Hua's complaint about the customer who ...,No,Did Li Hua's complaint about the customer who ...,"[{""id"":0,""content"":""Time: 20260330_08:00\nHail...",---Role---\n\nYou are a helpful assistant resp...,The complaint about the customer modifying the...,Li Hua's complaint about a client modifying th...
12,Did Yuriko tell Li Hua about booking a seat at...,Yes,Did Yuriko tell Li Hua about booking a seat at...,"[{""id"":0,""content"":""Time: 20260309_10:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Yes, according to the conversation, Yuriko inf...","Yuriko had previously booked a seat at ""Centra..."
13,What time does Li Hua check in with Adam about...,17:30,What time does Li Hua check in with Adam about...,"[{""id"":0,""content"":""Time: 20260105_14:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua checks in with Adam about the details f...,Li Hua checks in with Adam about moving in aro...
14,When was the first time Li Hua had dinner with...,20260108,When was the first time Li Hua had dinner with...,"[{""id"":0,""content"":""Time: 20260105_11:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,The first documented instance of Li Hua and Wo...,Li Hua and Wolfgang first had dinner together ...
15,Where was the first time Li Hua had dinner wit...,the cozy café downtown,Where was the first time Li Hua had dinner wit...,"[{""id"":0,""content"":""Time: 20260105_11:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,The first recorded instance of Li Hua having d...,Li Hua and Wolfgang had dinner at a cozy café ...
16,What time is Li Hua's lunch with Wolfgang Schu...,20260108,What time is Li Hua's lunch with Wolfgang Schu...,"[{""id"":0,""content"":""Time: 20260108_11:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversation, Li Hua and Wolf...",Li Hua's lunch with Wolfgang Schulz at the coz...
17,What is the Wi-Fi password at Li Hua's house?,Family123,What is the Wi-Fi password at Li Hua's house?,"[{""id"":0,""content"":""Time: 20260106_09:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the information provided, the Wi-Fi p...","Li Hua's house has a Wi-Fi password of ""Family..."
18,What does Adam say about having friends over?,having friends over occasionally is fine,What does Adam say about having friends over?,"[{""id"":0,""content"":""Time: 20260106_09:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"In the conversation, Adam provides detailed in...",AdamSmith mentioned that having friends over o...
19,What house rule does Adam mention?,keep noise to a minimum during late hours,What house rule does Adam mention?,"[{""id"":0,""content"":""Time: 20260109_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Adam mentions a couple of house rules in the c...,Adam mentions that Li Hua should keep noise to...
20,What does Li Hua report to Adam on January 6th?,the water tab in the apartment is broken,What does Li Hua report to Adam on January 6th?,"[{""id"":0,""content"":""Time: 20260330_18:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,"On January 6th, at 9:00 AM, Li Hua communicate...",Li Hua reports to Adam on January 6th that she...
21,When does Adam confirm the plumber will arrive?,tomorrow at 10 AM,When does Adam confirm the plumber will arrive?,"[{""id"":0,""content"":""Time: 20260106_15:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversation, Adam confirms t...",Adam confirms that the plumber will arrive tom...
22,What does Li Hua ask Adam about the door hinge?,a small repair,What does Li Hua ask Adam about the door hinge?,"[{""id"":0,""content"":""Time: 20260109_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua initially reached out to Adam Smith abo...,Li Hua asked Adam about the possibility of get...
23,What is the name of the gym that Wolfgang reco...,FitZone,What is the name of the gym that Wolfgang reco...,"[{""id"":0,""content"":""Time: 20260318_14:27\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Wolfgang recommended LiHua to go to a gym call...,Wolfgang recommended that LiHua check out FitZ...
24,When does Li Hua ask Jennifer Moore about adju...,20260122,When does Li Hua ask Jennifer Moore about adju...,"[{""id"":0,""content"":""Time: 20260115_16:45\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua reaches out to Jennifer Moore about adj...,Li Hua asks Jennifer Moore about adjusting the...
25,"What time does Li Hua watch the movie ""Overwat...",20260122,"What time does Li Hua watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260121_13:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,Based on the information provided in the conve...,Li Hua and Wolfgang Schulz plan to catch the 7...
26,"Who does Li Hua go to watch the movie ""Overwat...",Wolfgang,"Who does Li Hua go to watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260118_12:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversation provided, WolfgangSc...","Li Hua goes to watch the movie ""Overwatch 3"" w..."
27,When does Li Hua plan to celebrate Chinese Lun...,20260118,When does Li Hua plan to celebrate Chinese Lun...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua plans to celebrate Chinese Lunar New Ye...,Li Hua plans to celebrate Chinese Lunar New Ye...
28,What does Li Hua plan to celebrate Chinese Lun...,dumplings,What does Li Hua plan to celebrate Chinese Lun...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua plans to celebrate Chinese Lunar New Ye...,Li Hua plans to celebrate Chinese Lunar New Ye...
29,Who does Li Hua plan to celebrate Chinese Luna...,Wolfgang,Who does Li Hua plan to celebrate Chinese Luna...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua plans to celebrate Chinese Lunar New Ye...,Li Hua plans to celebrate Chinese Lunar New Ye...
30,Li Hua accidentally broke a light fixture once...,I'll arrange for a professional to take a look,Li Hua accidentally broke a light fixture once...,"[{""id"":0,""content"":""Time: 20260108_19:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"In a conversation dated 20260108_19:00, Li Hua...",Li Hua accidentally broke a light fixture in t...
31,Li Hua has a difficult client. When did he sol...,20260209,Li Hua has a difficult client. When did he sol...,"[{""id"":0,""content"":""Time: 20260210_21:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"According to the records, Li Hua solved the di...","Li Hua secured that difficult client, but the ..."
32,When did Li Hua express frustration about a cl...,20260131_14:00,When did Li Hua express frustration about a cl...,"[{""id"":0,""content"":""Time: 20260311_10:15\nYuri...",---Role---\n\nYou are a helpful assistant resp...,Li Hua expressed frustration about a client ch...,Li Hua expressed frustration about a client ch...
33,Who suggested Li Hua keep a clear log of all t...,Wolfgang Schulz,Who suggested Li Hua keep a clear log of all t...,"[{""id"":0,""content"":""Time: 20260123_17:30\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversation, Wolfgang Schulz...",Li Hua suggested keeping a clear log of all th...
34,What did Wolfgang Schulz suggest Li Hua to do ...,keep a clear log of all the changes requested ...,What did Wolfgang Schulz suggest Li Hua to do ...,"[{""id"":0,""content"":""Time: 20260105_11:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,When Li Hua faced a challenging client who kep...,Wolfgang Schulz suggested that Li Hua should k...
35,What does Li Hua plan to do to clear their head?,go for a walk and find a new café,What does Li Hua plan to do to clear their head?,"[{""id"":0,""content"":""Time: 20260311_10:15\nYuri...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversations recorded, Li Hua re...",Li Hua plans to go to a gym or fitness center ...
36,What is the name of the café Wolfgang Schulz r...,The Java Spot,What is the name of the café Wolfgang Schulz r...,"[{""id"":0,""content"":""Time: 20260108_11:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,According to the interactions detailed in the ...,"Wolfgang Schulz recommends a café called ""The ..."
37,Can Li Hua hang his artworks on the wall?,Yes,Can Li Hua hang his artworks on the wall?,"[{""id"":0,""content"":""Time: 20260201_20:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversation, Li Hua can indeed h...",Li Hua had inquired about hanging his artworks...
38,What does Adam Smith suggest Li Hua use to han...,use removable hooks,What does Adam Smith suggest Li Hua use to han...,"[{""id"":0,""content"":""Time: 20260201_20:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,According to the conversations between Li Hua ...,Adam Smith suggests that Li Hua use removable ...
39,How many times does Li Hua train per week now?,2,How many times does Li Hua train per week now?,"[{""id"":0,""content"":""Time: 20260204_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the interactions provided, there isn'...","Li Hua now trains twice a week, with sessions ..."
40,When did Li Hua change the training plan?,20260204,When did Li Hua change the training plan?,"[{""id"":0,""content"":""Time: 20260112_15:00\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua did not explicitly change the training ...,Li Hua changed the training plan to train twic...
41,What days does Li Hua takes for the training s...,Tuesdays and Thursdays,What days does Li Hua takes for the training s...,"[{""id"":0,""content"":""Time: 20260204_15:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversations provided, there are...","Li Hua takes training sessions twice a week, o..."
42,When did Li Hua ask Jennifer Moore for tips on...,20260206_16:00,When did Li Hua ask Jennifer Moore for tips on...,"[{""id"":0,""content"":""Time: 20260206_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua asked Jennifer Moore for tips on dealin...,Li Hua asked Jennifer Moore for tips on dealin...
43,What are some of Jennifer Moore's tips for dea...,hydration&active recovery&stretching&foam roll...,What are some of Jennifer Moore's tips for dea...,"[{""id"":0,""content"":""Time: 20260206_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Jennifer Moore provides several tips for deali...,Jennifer Moore suggests that dealing with musc...
44,Why did Li Hua ask for extra exercises to do a...,to complement his training schedule,Why did Li Hua ask for extra exercises to do a...,"[{""id"":0,""content"":""Time: 20260325_19:00\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua reached out to Jennifer Moore for extra...,Li Hua asked for extra exercises to do at home...
45,What exercises did Jennifer Moore suggest Li H...,bodyweight squats& plank holds&push-ups&lunges...,What exercises did Jennifer Moore suggest Li H...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Based on the conversations documented in the d...,Jennifer Moore suggested that Li Hua do the fo...
46,What is Adam Smith's condition for Li Hua to a...,must be reversible and not damage anything,What is Adam Smith's condition for Li Hua to a...,"[{""id"":0,""content"":""Time: 20260108_19:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversations, Adam Smith has...",Adam Smith has stated that as long as the deco...
47,When was the first time Wolfgang went to Li Hu...,20260221,When was the first time Wolfgang went to Li Hu...,"[{""id"":0,""content"":""Time: 20260301_13:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,The first mention of Wolfgang visiting Li Hua'...,"Based on the provided conversation history, th..."
48,What ideas did Wolfgang Schulz suggest for Li ...,good lighting&soundproofing&a comfy chair,What ideas did Wolfgang Schulz suggest for Li ...,"[{""id"":0,""content"":""Time: 20260105_11:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,In the conversations regarding Wolfgang Schulz...,Wolfgang Schulz suggested several ideas for Li...
49,Why did Adam remind Li Hua not to play guitar ...,a few neighbors have mentioned they're hearing...,Why did Adam remind Li Hua not to play guitar ...,"[{""id"":0,""content"":""Time: 20260218_18:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,Adam reminded Li Hua not to play guitar late a...,Adam reminded Li Hua not to play guitar late a...
50,What type of ambiance does YurikoYamamoto want...,more welcoming and engaging,NaN,NaN,NaN,CUDA out of memory. Tried to allocate 2.10 GiB...,"Unfortunately, there is no context provided, r..."
51,When did Li Hua invite Adam Smith to check the...,20260223_19:00,When did Li Hua invite Adam Smith to check the...,"[{""id"":0,""content"":""Time: 20260223_17:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua invited Adam Smith to check the progres...,Li Hua invited Adam Smith to check the basemen...
52,What is the name of the café where Li Hua and ...,Central Perk,What is the name of the café where Li Hua and ...,"[{""id"":0,""content"":""Time: 20260312_16:00\nYuri...",---Role---\n\nYou are a helpful assistant resp...,Li Hua and YurikoYamamoto first met at Central...,Li Hua and YurikoYamamoto first met to discuss...
53,What is the essence of YurikoYamamoto Li Hua i...,speech therapy,What is the essence of YurikoYamamoto Li Hua i...,"[{""id"":0,""content"":""Time: 20260311_14:30\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,YurikoYamamoto is seeking Li Hua's assistance ...,YurikoYamamoto is working on improving her spe...
54,What type of instrument does Li Hua play in th...,guitar,NaN,NaN,NaN,CUDA out of memory. Tried to allocate 2.07 GiB...,I couldn't find any information on Li Hua or t...
55,When did Adam Smith inform Li Hua about potent...,20260301_13:00,When did Adam Smith inform Li Hua about potent...,"[{""id"":0,""content"":""Time: 20260301_13:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversation, Adam Smith info...",Adam Smith informed Li Hua about potential iss...
56,When did Li Hua inform Adam Smith that the ren...,20260301_10:00,When did Li Hua inform Adam Smith that the ren...,"[{""id"":0,""content"":""Time: 20260331_17:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua informed Adam Smith about the transfer ...,Li Hua informed Adam Smith that the rent was t...
57,When is the music concert that Wolfgang invite...,20260307_18:00,NaN,NaN,NaN,CUDA out of memory. Tried to allocate 9.22 GiB...,"There is no context information provided, as t..."

In [ ]:
# print(df['sys_prompt'][0])

In [ ]:
def generate_relevant_only_prompt(sys_prompt, relevant_context):
    if type(sys_prompt)!=str:
        return ""
    prompt = sys_prompt
    substring = "-----Sources-----"

    index = prompt.find(substring)

    if index != -1:
        selected_prompt = prompt[:index]
    else:
        selected_prompt=""

    return selected_prompt+"\n\n-----Sources-----\n\n"+relevant_context+"""```\n\nAdd sections and commentary to the response as appropriate for the length and format. Style the response in markdown."""

In [ ]:
df['relevant_sys_prompt']=df.apply(lambda x: generate_relevant_only_prompt(x['sys_prompt'], x['relevant_context']), axis=1)

In [ ]:
df

,Question,Gold Answer,query,context_json_data,sys_prompt,minirag,relevant_context,relevant_sys_prompt
0,Did Li Hua send a message to Jennifer thanking...,Yes,Did Li Hua send a message to Jennifer thanking...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Based on the information provided in the messa...,Li Hua sent a message to Jennifer thanking her...,---Role---\n\nYou are a helpful assistant resp...
1,Did Yuriko ask Li Hua for help with her studio...,Yes,Did Yuriko ask Li Hua for help with her studio...,"[{""id"":0,""content"":""Time: 20260309_10:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Yes, according to the conversation, Yuriko did...",Yuriko did ask Li Hua for help with her studio...,---Role---\n\nYou are a helpful assistant resp...
2,Did Li Hua send a message to Jennifer asking i...,Yes,Did Li Hua send a message to Jennifer asking i...,"[{""id"":0,""content"":""Time: 20260309_12:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Yes, Li Hua did request a change in his traini...",Li Hua sent a message to Jennifer asking if he...,---Role---\n\nYou are a helpful assistant resp...
3,"What time does Li Hua watch the movie ""Overwat...",20260122,"What time does Li Hua watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260121_13:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversation shared, WolfgangSchu...","Li Hua plans to watch the movie ""Overwatch 3"" ...",---Role---\n\nYou are a helpful assistant resp...
4,"Who does Li Hua go to watch the movie ""Overwat...",Wolfgang,"Who does Li Hua go to watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260121_13:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,Based on the information provided in the conve...,"Li Hua plans to watch the movie ""Overwatch 3"" ...",---Role---\n\nYou are a helpful assistant resp...
5,Who wished Li Hua a happy Lunar New Year?,Adam Smith & Jennifer Moore & Wolfgang Schulz,Who wished Li Hua a happy Lunar New Year?,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,"In the conversation, Jennifer Moore wished Li ...",Li Hua received happy Lunar New Year wishes fr...,---Role---\n\nYou are a helpful assistant resp...
6,Who introduced the bread delivery service and ...,HaileyJohnson,NaN,NaN,NaN,CUDA out of memory. Tried to allocate 2.14 GiB...,I couldn't find any information in the provide...,
7,What is the opportunity that makes Wolfgang an...,LiHua introduce them to each other by saying t...,NaN,NaN,NaN,CUDA out of memory. Tried to allocate 2.01 GiB...,I couldn't find any relevant information in th...,
8,What was the content of the first-ever deliver...,a fresh sourdough loaf and a bottle of milk an...,What was the content of the first-ever deliver...,"[{""id"":0,""content"":""Time: 20260314_17:00\nHail...",---Role---\n\nYou are a helpful assistant resp...,The first-ever delivery from Hailey Johnson to...,Hailey initially offered LiHua a doorstep deli...,---Role---\n\nYou are a helpful assistant resp...
9,Did Li Hua send a message to Wolfgang Schulz s...,Yes,Did Li Hua send a message to Wolfgang Schulz s...,"[{""id"":0,""content"":""Time: 20260318_14:27\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"No, there is no mention in the provided data o...",Li Hua had previously sent a message to Wolfga...,---Role---\n\nYou are a helpful assistant resp...
10,Did Li Hua provide feedback to Jennifer Moore ...,No,Did Li Hua provide feedback to Jennifer Moore ...,"[{""id"":0,""content"":""Time: 20260115_16:45\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"In the conversation, Li Hua did not explicitly...",Li Hua provided feedback to Jennifer Moore on ...,---Role---\n\nYou are a helpful assistant resp...
11,Did Li Hua's complaint about the customer who ...,No,Did Li Hua's complaint about the customer who ...,"[{""id"":0,""content"":""Time: 20260330_08:00\nHail...",---Role---\n\nYou are a helpful assistant resp...,The complaint about the customer modifying the...,Li Hua's complaint about a client modifying th...,---Role---\n\nYou are a helpful assistant resp...
12,Did Yuriko tell Li Hua about booking a seat at...,Yes,Did Yuriko tell Li Hua about booking a seat at...,"[{""id"":0,""content"":""Time: 20260309_10:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Yes, according to the conversation, Yuriko inf...","Yuriko had previously booked a seat at ""Centra...",---Role---\n\nYou are a helpful assistant resp...
13,What time does Li Hua check in with Adam about...,17:30,What time does Li Hua check in with Adam about...,"[{""id"":0,""content"":""Time: 20260105_14:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua checks in with Adam about the details f...,Li Hua checks in with Adam about moving in aro...,---Role---\n\nYou are a helpful assistant resp...
14,When was the first time Li Hua had dinner with...,20260108,When was the first time Li Hua had dinner with...,"[{""id"":0,""content"":""Time: 20260105_11:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,The first documented instance of Li Hua and Wo...,Li Hua and Wolfgang first had dinner together ...,---Role---\n\nYou are a helpful assistant resp...
15,Where was the first time Li Hua had dinner wit...,the cozy café downtown,Where was the first time Li Hua had dinner wit...,"[{""id"":0,""content"":""Time: 20260105_11:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,The first recorded instance of Li Hua having d...,Li Hua and Wolfgang had dinner at a cozy café ...,---Role---\n\nYou are a helpful assistant resp...
16,What time is Li Hua's lunch with Wolfgang Schu...,20260108,What time is Li Hua's lunch with Wolfgang Schu...,"[{""id"":0,""content"":""Time: 20260108_11:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversation, Li Hua and Wolf...",Li Hua's lunch with Wolfgang Schulz at the coz...,---Role---\n\nYou are a helpful assistant resp...
17,What is the Wi-Fi password at Li Hua's house?,Family123,What is the Wi-Fi password at Li Hua's house?,"[{""id"":0,""content"":""Time: 20260106_09:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the information provided, the Wi-Fi p...","Li Hua's house has a Wi-Fi password of ""Family...",---Role---\n\nYou are a helpful assistant resp...
18,What does Adam say about having friends over?,having friends over occasionally is fine,What does Adam say about having friends over?,"[{""id"":0,""content"":""Time: 20260106_09:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"In the conversation, Adam provides detailed in...",AdamSmith mentioned that having friends over o...,---Role---\n\nYou are a helpful assistant resp...
19,What house rule does Adam mention?,keep noise to a minimum during late hours,What house rule does Adam mention?,"[{""id"":0,""content"":""Time: 20260109_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Adam mentions a couple of house rules in the c...,Adam mentions that Li Hua should keep noise to...,---Role---\n\nYou are a helpful assistant resp...
20,What does Li Hua report to Adam on January 6th?,the water tab in the apartment is broken,What does Li Hua report to Adam on January 6th?,"[{""id"":0,""content"":""Time: 20260330_18:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,"On January 6th, at 9:00 AM, Li Hua communicate...",Li Hua reports to Adam on January 6th that she...,---Role---\n\nYou are a helpful assistant resp...
21,When does Adam confirm the plumber will arrive?,tomorrow at 10 AM,When does Adam confirm the plumber will arrive?,"[{""id"":0,""content"":""Time: 20260106_15:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversation, Adam confirms t...",Adam confirms that the plumber will arrive tom...,---Role---\n\nYou are a helpful assistant resp...
22,What does Li Hua ask Adam about the door hinge?,a small repair,What does Li Hua ask Adam about the door hinge?,"[{""id"":0,""content"":""Time: 20260109_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua initially reached out to Adam Smith abo...,Li Hua asked Adam about the possibility of get...,---Role---\n\nYou are a helpful assistant resp...
23,What is the name of the gym that Wolfgang reco...,FitZone,What is the name of the gym that Wolfgang reco...,"[{""id"":0,""content"":""Time: 20260318_14:27\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Wolfgang recommended LiHua to go to a gym call...,Wolfgang recommended that LiHua check out FitZ...,---Role---\n\nYou are a helpful assistant resp...
24,When does Li Hua ask Jennifer Moore about adju...,20260122,When does Li Hua ask Jennifer Moore about adju...,"[{""id"":0,""content"":""Time: 20260115_16:45\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua reaches out to Jennifer Moore about adj...,Li Hua asks Jennifer Moore about adjusting the...,---Role---\n\nYou are a helpful assistant resp...
25,"What time does Li Hua watch the movie ""Overwat...",20260122,"What time does Li Hua watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260121_13:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,Based on the information provided in the conve...,Li Hua and Wolfgang Schulz plan to catch the 7...,---Role---\n\nYou are a helpful assistant resp...
26,"Who does Li Hua go to watch the movie ""Overwat...",Wolfgang,"Who does Li Hua go to watch the movie ""Overwat...","[{""id"":0,""content"":""Time: 20260118_12:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversation provided, WolfgangSc...","Li Hua goes to watch the movie ""Overwatch 3"" w...",---Role---\n\nYou are a helpful assistant resp...
27,When does Li Hua plan to celebrate Chinese Lun...,20260118,When does Li Hua plan to celebrate Chinese Lun...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua plans to celebrate Chinese Lunar New Ye...,Li Hua plans to celebrate Chinese Lunar New Ye...,---Role---\n\nYou are a helpful assistant resp...
28,What does Li Hua plan to celebrate Chinese Lun...,dumplings,What does Li Hua plan to celebrate Chinese Lun...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua plans to celebrate Chinese Lunar New Ye...,Li Hua plans to celebrate Chinese Lunar New Ye...,---Role---\n\nYou are a helpful assistant resp...
29,Who does Li Hua plan to celebrate Chinese Luna...,Wolfgang,Who does Li Hua plan to celebrate Chinese Luna...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua plans to celebrate Chinese Lunar New Ye...,Li Hua plans to celebrate Chinese Lunar New Ye...,---Role---\n\nYou are a helpful assistant resp...
30,Li Hua accidentally broke a light fixture once...,I'll arrange for a professional to take a look,Li Hua accidentally broke a light fixture once...,"[{""id"":0,""content"":""Time: 20260108_19:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"In a conversation dated 20260108_19:00, Li Hua...",Li Hua accidentally broke a light fixture in t...,---Role---\n\nYou are a helpful assistant resp...
31,Li Hua has a difficult client. When did he sol...,20260209,Li Hua has a difficult client. When did he sol...,"[{""id"":0,""content"":""Time: 20260210_21:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"According to the records, Li Hua solved the di...","Li Hua secured that difficult client, but the ...",---Role---\n\nYou are a helpful assistant resp...
32,When did Li Hua express frustration about a cl...,20260131_14:00,When did Li Hua express frustration about a cl...,"[{""id"":0,""content"":""Time: 20260311_10:15\nYuri...",---Role---\n\nYou are a helpful assistant resp...,Li Hua expressed frustration about a client ch...,Li Hua expressed frustration about a client ch...,---Role---\n\nYou are a helpful assistant resp...
33,Who suggested Li Hua keep a clear log of all t...,Wolfgang Schulz,Who suggested Li Hua keep a clear log of all t...,"[{""id"":0,""content"":""Time: 20260123_17:30\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversation, Wolfgang Schulz...",Li Hua suggested keeping a clear log of all th...,---Role---\n\nYou are a helpful assistant resp...
34,What did Wolfgang Schulz suggest Li Hua to do ...,keep a clear log of all the changes requested ...,What did Wolfgang Schulz suggest Li Hua to do ...,"[{""id"":0,""content"":""Time: 20260105_11:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,When Li Hua faced a challenging client who kep...,Wolfgang Schulz suggested that Li Hua should k...,---Role---\n\nYou are a helpful assistant resp...
35,What does Li Hua plan to do to clear their head?,go for a walk and find a new café,What does Li Hua plan to do to clear their head?,"[{""id"":0,""content"":""Time: 20260311_10:15\nYuri...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversations recorded, Li Hua re...",Li Hua plans to go to a gym or fitness center ...,---Role---\n\nYou are a helpful assistant resp...
36,What is the name of the café Wolfgang Schulz r...,The Java Spot,What is the name of the café Wolfgang Schulz r...,"[{""id"":0,""content"":""Time: 20260108_11:00\nWolf...",---Role---\n\nYou are a helpful assistant resp...,According to the interactions detailed in the ...,"Wolfgang Schulz recommends a café called ""The ...",---Role---\n\nYou are a helpful assistant resp...
37,Can Li Hua hang his artworks on the wall?,Yes,Can Li Hua hang his artworks on the wall?,"[{""id"":0,""content"":""Time: 20260201_20:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversation, Li Hua can indeed h...",Li Hua had inquired about hanging his artworks...,---Role---\n\nYou are a helpful assistant resp...
38,What does Adam Smith suggest Li Hua use to han...,use removable hooks,What does Adam Smith suggest Li Hua use to han...,"[{""id"":0,""content"":""Time: 20260201_20:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,According to the conversations between Li Hua ...,Adam Smith suggests that Li Hua use removable ...,---Role---\n\nYou are a helpful assistant resp...
39,How many times does Li Hua train per week now?,2,How many times does Li Hua train per week now?,"[{""id"":0,""content"":""Time: 20260204_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the interactions provided, there isn'...","Li Hua now trains twice a week, with sessions ...",---Role---\n\nYou are a helpful assistant resp...
40,When did Li Hua change the training plan?,20260204,When did Li Hua change the training plan?,"[{""id"":0,""content"":""Time: 20260112_15:00\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua did not explicitly change the training ...,Li Hua changed the training plan to train twic...,---Role---\n\nYou are a helpful assistant resp...
41,What days does Li Hua takes for the training s...,Tuesdays and Thursdays,What days does Li Hua takes for the training s...,"[{""id"":0,""content"":""Time: 20260204_15:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"Based on the conversations provided, there are...","Li Hua takes training sessions twice a week, o...",---Role---\n\nYou are a helpful assistant resp...
42,When did Li Hua ask Jennifer Moore for tips on...,20260206_16:00,When did Li Hua ask Jennifer Moore for tips on...,"[{""id"":0,""content"":""Time: 20260206_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua asked Jennifer Moore for tips on dealin...,Li Hua asked Jennifer Moore for tips on dealin...,---Role---\n\nYou are a helpful assistant resp...
43,What are some of Jennifer Moore's tips for dea...,hydration&active recovery&stretching&foam roll...,What are some of Jennifer Moore's tips for dea...,"[{""id"":0,""content"":""Time: 20260206_16:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Jennifer Moore provides several tips for deali...,Jennifer Moore suggests that dealing with musc...,---Role---\n\nYou are a helpful assistant resp...
44,Why did Li Hua ask for extra exercises to do a...,to complement his training schedule,Why did Li Hua ask for extra exercises to do a...,"[{""id"":0,""content"":""Time: 20260325_19:00\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Li Hua reached out to Jennifer Moore for extra...,Li Hua asked for extra exercises to do at home...,---Role---\n\nYou are a helpful assistant resp...
45,What exercises did Jennifer Moore suggest Li H...,bodyweight squats& plank holds&push-ups&lunges...,What exercises did Jennifer Moore suggest Li H...,"[{""id"":0,""content"":""Time: 20260119_14:30\nJenn...",---Role---\n\nYou are a helpful assistant resp...,Based on the conversations documented in the d...,Jennifer Moore suggested that Li Hua do the fo...,---Role---\n\nYou are a helpful assistant resp...
46,What is Adam Smith's condition for Li Hua to a...,must be reversible and not damage anything,What is Adam Smith's condition for Li Hua to a...,"[{""id"":0,""content"":""Time: 20260108_19:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,"According to the conversations, Adam Smith has...",Adam Smith has stated that as long as the deco...,---Role---\n\nYou are a helpful assistant resp...
47,When was the first time Wolfgang went to Li Hu...,20260221,When was the first time Wolfgang went to Li Hu...,"[{""id"":0,""content"":""Time: 20260301_13:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,The first mention of Wolfgang visiting Li Hua'...,"Based on the provided conversation history, th...",---Role---\n\nYou are a helpful assistant resp...
48,What ideas did Wolfgang Schulz suggest for Li ...,good lighting&soundproofing&a comfy chair,What ideas did Wolfgang Schulz suggest for Li ...,"[{""id"":0,""content"":""Time: 20260105_11:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,In the conversations regarding Wolfgang Schulz...,Wolfgang Schulz suggested several ideas for Li...,---Role---\n\nYou are a helpful assistant resp...
49,Why did Adam remind Li Hua not to play guitar ...,a few neighbors have mentioned they're hearing...,Why did Adam remind Li Hua not to play guitar ...,"[{""id"":0,""content"":""Time: 20260218_18:00\nAdam...",---Role---\n\nYou are a helpful assistant resp...,Adam reminded Li Hua not to play guitar late a...,Adam reminded Li Hua not to play guitar late a...,---Role---\n\nYou are a helpful assistant resp...
50,What type of ambiance does YurikoYamamoto want...,more welcoming and engaging,NaN,NaN,NaN,CUDA out of memory. Tried to allocate 2.10 GiB...,"Unfortunately, there is no context provided, r...",
51,When did Li Hua invite Adam Smith to check the...,20260223_19:00,When did Li Hua invite Adam Smith to check the...,"[{""id"":0,""content"":""Time: 20260223_17:00\nLiHu...",---Role---\n\nYou are a helpful assistant resp...,Li Hua invited Adam Smith to check the progres...,Li Hua invited Adam Smith to check the basemen...,---Role---\n\nYou are a helpful assistant resp...
52,What is the name of the café where Li Hua and ...,Central Perk,What is the name of the café where Li Hua and ...,"[{""id"":0,""content"":""Time: 20260312_16:00\nYuri...",---Role---\n\nYou are a helpful assistant resp...,Li Hua and YurikoYamamoto first met at Central...,Li Hua and YurikoYamamoto first met to discuss...,---Role---\n\nYou are a helpful assistant resp...

In [ ]:
# from transformers import pipeline

# pipe = pipeline("text-generation", model="Qwen/Qwen2.5-3B-Instruct")
# messages = [
#     {"role": "user", "content": "Who are you?"},
# ]
# pipe(messages)

In [ ]:
df['Question'][0]

'Did Li Hua send a message to Jennifer thanking her for the new training schedule before he requested a change in his training schedule for Thursday?'

In [ ]:
def get_relevant_context_response(Question, relevant_sys_prompt):
    messages = [
        {"role": "system", "content": f"{relevant_sys_prompt}"},
        {"role": "user", "content": f"{Question}"},
    ]
    a=pipe(messages)
    return a[0]['generated_text'][2]['content']

In [ ]:
df['relevant_context_response']=df.apply(lambda x: get_relevant_context_response(x['Question'], x['relevant_sys_prompt']), axis=1)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df.to_csv("relevant_context_v4_llama.csv", index=False)

In [ ]:
df

In [ ]:
# df=pd.read_csv("/content/relevant_context2.csv")

In [ ]:
# def get_answer_judgement(question, ground_truth, response):
#     client = genai.Client(
#         api_key="AIzaSyAvsjjJ8c31-y3Rwa7yNzb7h8HwDB5y3A8",
#     )

#     model = "gemini-2.5-flash"
#     contents = [
#         types.Content(
#             role="user",
#             parts=[
#                 types.Part.from_text(text=
#                 f"""You are a **judge agent**. Compare the **Ground Truth Answer** and **Generated Response** to decide if they mean the same.
# Output only one word: `CORRECT` or `INCORRECT`.

# ### INPUT
# Question: [for context only]
# Ground Truth Answer: [...]
# Generated Response: [...]

# ### RULES
# 1. Compare meaning; ignore punctuation, casing, and phrasing.
# 2. Accept synonyms or paraphrases if meaning unchanged.
# 3. Numbers: ±1% tolerance; allow simple unit conversions.
# 4. Lists/sets: all required items must appear (order irrelevant).
# 5. Yes/No: must match exactly.
# 6. If response is empty, irrelevant, or wrong → `INCORRECT`.
# 7. Extra explanation is fine if main answer is correct.

# ### OUTPUT
# Only:
# - `CORRECT`
# - `INCORRECT`

# Optionally, a short 1-line reason (<20 words).

# Example:
# Q: Capital of France
# GT: Paris
# Resp: The capital is Paris
# → CORRECT

# Question: {question}
# Ground Truth Answer: {ground_truth}
# Generated Response:{response}
#                 """),
#             ],
#         ),
#     ]


#     response = client.models.generate_content(
#         model=model,
#         contents=contents,

#     )
#     # print(response)
#     time.sleep(5)
#     return response.text

In [ ]:
# df['minirag_eval']=df.apply(lambda x: get_answer_judgement(x['Question'], x['Gold Answer'], x['minirag']), axis=1)

In [ ]:
# df['relevant_minirag_eval']=df.apply(lambda x: get_answer_judgement(x['Question'], x['Gold Answer'], x['relevant_context_response']), axis=1)

In [ ]:
# df.to_csv("relevant_context3.csv", index=False)

In [ ]:
# df=pd.read_csv("relevant_context3.csv")

In [ ]:
# df['relevant_minirag_acc']=df['relevant_minirag_eval'].apply(lambda x: ast.literal_eval(x.strip("```json").strip("```"))['judgment'])

In [ ]:
# import pandas as pd
# import json
# import re
# import ast


# # Function to dynamically extract and parse JSON/dict content
# def extract_json_value(text, key="judgment"):
#     if not isinstance(text, str):
#         return None

#     # Find JSON-like substring inside {}
#     match = re.search(r"\{.*\}", text, re.DOTALL)
#     if not match:
#         return None

#     content = match.group(0).strip()

#     try:
#         # Try JSON first
#         obj = json.loads(content)
#     except json.JSONDecodeError:
#         try:
#             # Fallback to Python dict format (e.g. single quotes)
#             obj = ast.literal_eval(content)
#         except Exception:
#             return None

#     return obj.get(key)

# # Apply dynamically
# df["minirag_acc"] = df["minirag_eval"].apply(lambda x: extract_json_value(x, "judgment"))

# # print(df[["minirag_eval", "judgment"]])

In [ ]:
# df['relevant_minirag_acc'].value_counts()